import Head from "next/head";
import { Badge } from "./components/badge";
import { Button } from "./components/button";
import { Card } from "./components/card";
import {
    Accordion,
    AccordionContent,
    AccordionItem,
    AccordionTrigger,
  } from "./components/accordion";

import { Check, Image as ImageIcon, Sparkles, Zap } from "lucide-react";
import Image from "next/image";
import { useRouter } from "next/router";
import { useSession } from "next-auth/react";


export default function Home() {

    const {data: session, status} = useSession()
    const navigate = useRouter()
    const handleClick = () =>{
        if(status === "authenticated"){
            navigate.push("/generate")
        }else{
            navigate.push("/login")
        }
    }

    const faqs = [
        {
          question: "How does the cartoonification process work?",
          answer: "Our AI technology analyzes your photo and applies advanced algorithms to transform it into a cartoon style while preserving key features and details."
        },
        {
          question: "What image formats are supported?",
          answer: "We support most common image formats including JPG, PNG, and WEBP files up to 10MB in size."
        },
        {
          question: "How long does the process take?",
          answer: "Most images are processed within seconds, though complex images might take up to a minute."
        },
        {
          question: "Can I customize the cartoon style?",
          answer: "Currently, we offer our signature cartoon style. More style options will be available soon!"
        }
      ];
  return (
    <>
      <Head>
        <title>CartoonTrait</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main className="bg-base-100 min-h-screen">
        {/* Hero Section */}
        <section className="w-full max-w-7xl mx-auto flex flex-col items-center justify-center space-y-6 pt-24 text-center md:pt-32 px-4 md:px-8">
          <Badge className="mb-4" variant="secondary">
            ✨ Transform your photos into cartoons
          </Badge>
          <h1 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl lg:text-6xl">
            Turn Your Photos into
            <span className="bg-gradient-to-r from-purple-400 to-pink-600 bg-clip-text text-transparent">
              {" "}
              Cartoon Art
            </span>
          </h1>
          <p className="max-w-[700px] text-base text-muted-foreground sm:text-lg md:text-xl">
            Transform your photos into stunning cartoon masterpieces with our
            AI-powered service. Fast, affordable, and amazing results.
          </p>
          <div className="flex flex-col gap-4 sm:flex-row">
            <Button size="lg" className="w-full sm:w-auto" onClick={handleClick}>
              <Sparkles className="mr-2 h-4 w-4" />
              Try it now
            </Button>
            <Button size="lg" variant="outline" className="w-full sm:w-auto">
              View Examples
            </Button>
          </div>
          <div className="relative mt-8 aspect-[2/1] w-full max-w-3xl overflow-hidden rounded-lg border">
            <Image
              src="/mainimage.png"
              alt="Example transformation"
              fill
              className="object-cover"
              sizes="(max-width: 768px) 100vw, (max-width: 1200px) 80vw, 1200px"
            />
          </div>
        </section>
        {/* Content Section 1 */}
        
        <section className="w-full max-w-7xl mx-auto my-12 md:my-20 px-4 md:px-8">
          <div className="grid gap-6 md:grid-cols-3">
            <Card className="p-6">
              <Zap className="mb-4 h-8 w-8 text-purple-500" />
              <h3 className="mb-2 text-xl font-bold">Instant Results</h3>
              <p className="text-muted-foreground">
                Get your cartoonified images in seconds with our advanced AI technology.
              </p>
            </Card>
            <Card className="p-6">
              <ImageIcon className="mb-4 h-8 w-8 text-pink-500" />
              <h3 className="mb-2 text-xl font-bold">High Quality</h3>
              <p className="text-muted-foreground">
                Crystal clear outputs with stunning detail and vibrant colors.
              </p>
            </Card>
            <Card className="p-6">
              <Check className="mb-4 h-8 w-8 text-green-500" />
              <h3 className="mb-2 text-xl font-bold">Easy to Use</h3>
              <p className="text-muted-foreground">
                Simple upload and download process with no technical skills required.
              </p>
            </Card>
          </div>
        </section>
        <section id="pricing" className="w-full max-w-7xl mx-auto my-12 md:my-20 px-4 md:px-8">
          <h2 className="mb-8 md:mb-12 text-center text-2xl md:text-3xl font-bold">Simple Pricing</h2>
          <Card className="mx-auto max-w-md p-6 md:p-8 text-center">
            <h3 className="text-xl md:text-2xl font-bold">Pay As You Go</h3>
            <div className="my-4">
              <span className="text-3xl md:text-4xl font-bold">$0.50</span>
              <span className="text-muted-foreground"> / image</span>
            </div>
            <ul className="mb-8 space-y-4 text-left">
              <li className="flex items-center">
                <Check className="mr-2 h-4 w-4 text-green-500" />
                High-quality cartoon conversion
              </li>
              <li className="flex items-center">
                <Check className="mr-2 h-4 w-4 text-green-500" />
                Instant processing
              </li>
              <li className="flex items-center">
                <Check className="mr-2 h-4 w-4 text-green-500" />
                Download in multiple formats
              </li>
              <li className="flex items-center">
                <Check className="mr-2 h-4 w-4 text-green-500" />
                24/7 support
              </li>
            </ul>
            <Button className="w-full" onClick={handleClick}>Get Started</Button>
          </Card>
        </section>

        {/* FAQ Section */}
        <section id="faq" className="w-full max-w-7xl mx-auto my-12 md:my-20 px-4 md:px-8">
          <h2 className="mb-8 md:mb-12 text-center text-2xl md:text-3xl font-bold">
            Frequently Asked Questions
          </h2>
          <div className="mx-auto max-w-3xl">
            <Accordion type="single" collapsible className="w-full">
              {faqs.map((faq, index) => (
                <AccordionItem key={index} value={`item-${index}`}>
                  <AccordionTrigger className="text-left">{faq.question}</AccordionTrigger>
                  <AccordionContent>{faq.answer}</AccordionContent>
                </AccordionItem>
              ))}
            </Accordion>
          </div>
        </section>
        
      </main>
    </>
  );
}


